# Generated by Django 5.0 on 2026-06-24 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('SEDE', 'Sede Comando Regional'), ('INTEL', 'Inteligência'), ('5BPM', '5º BPM'), ('15BPM', '15º BPM'), ('28BPM', '28º BPM'), ('17CIPM', '17ª CIPM'), ('14CIPMFT', '14ª CIPM Força Tática')], max_length=50, unique=True, verbose_name='Nome da Unidade')),
                ('sigla', models.CharField(help_text='Ex: 5º BPM, 14ª CIPMFT', max_length=15, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunidade', models.CharField(blank=True, help_text='Ex: Força Tática, Rádio Patrulha, SGO', max_length=50, null=True, verbose_name='Subunidade / Setor')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa / Prefixo')),
                ('tipo', models.CharField(help_text='Ex: SUV, Pick-up, Sedan, Base Móvel', max_length=30, verbose_name='Tipo de Veículo')),
                ('modelo', models.CharField(help_text='Ex: Toyota Hilux, Renault Duster, Chevrolet S10', max_length=50, verbose_name='Modelo')),
                ('condicao', models.CharField(choices=[('BOM', 'Bom Estado'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim / Necessita Reparo')], default='BOM', max_length=10, verbose_name='Condição Geral')),
                ('km', models.PositiveIntegerField(verbose_name='Quilometragem (KM)')),
                ('situacao', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('BAIXADA', 'Baixada')], default='OPERACIONAL', max_length=15, verbose_name='Situação Atual')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações / Motivo da Baixa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaturas', to='vtr.unidade', verbose_name='Unidade Pertencente')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['unidade', 'situacao', 'modelo'],
            },
        ),
    ]
