# Generated by Django 5.0 on 2026-06-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ex: Toyota Hilux, Renault Duster, Chevrolet S10', max_length=100, unique=True, verbose_name='Modelo do Veículo')),
                ('tipo', models.CharField(choices=[('SUV', 'SUV'), ('PICK-UP', 'Pick-up'), ('SEDAN', 'Sedan'), ('BASE MOVEL', 'Base Móvel'), ('MOTOCICLETA', 'Motocicleta'), ('ONIBUS', 'Ônibus'), ('MICRO-ONIBUS', 'Micro-ônibus')], default='SUV', max_length=30, verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Modelo de Viatura',
                'verbose_name_plural': 'Modelos de Viaturas',
                'ordering': ['modelo'],
            },
        ),
        migrations.AlterModelOptions(
            name='viatura',
            options={'ordering': ['unidade', 'situacao', 'modelo_veiculo__modelo'], 'verbose_name': 'Viatura', 'verbose_name_plural': 'Viaturas'},
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='tipo',
        ),
        migrations.AddField(
            model_name='viatura',
            name='prefixo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prefixo / Código da Vtr'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(help_text='Ex: 5º Batalhão da Polícia Militar, Sede do Comando Regional', max_length=150, unique=True, verbose_name='Nome Completo da Unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(help_text='Ex: 5º BPM, 14ª CIPMFT, Inteligência', max_length=50, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='subunidade',
            field=models.CharField(blank=True, help_text='Ex: Força Tática, Rádio Patrulha, SGO', max_length=100, null=True, verbose_name='Subunidade / Setor'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='modelo_veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='vtr.modeloviatura', verbose_name='Modelo / Tipo de Veículo'),
            preserve_default=False,
        ),
    ]
