# Generated by Django 5.0 on 2026-07-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtr', '0002_modeloviatura_alter_viatura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_graduacao', models.CharField(choices=[('Al Sd PM', 'Al Sd PM (Aluno Soldado)'), ('Sd PM', 'Sd PM (Soldado)'), ('Cb PM', 'Cb PM (Cabo)'), ('3º Sgt PM', '3º Sgt PM (Terceiro Sargento)'), ('2º Sgt PM', '2º Sgt PM (Segundo Sargento)'), ('1º Sgt PM', '1º Sgt PM (Primeiro Sargento)'), ('Sub Ten PM', 'Sub Ten Ten PM (Subtenente)'), ('Asp Of PM', 'Asp Of PM (Aspirante a Oficial)'), ('2º Ten PM', '2º Ten PM (Segundo Tenente)'), ('1º Ten PM', '1º Ten PM (Primeiro Tenente)'), ('Cap PM', 'Cap PM (Capitão)'), ('Maj PM', 'Maj PM (Major)'), ('Ten Cel PM', 'Ten Cel PM (Tenente Coronel)'), ('Cel PM', 'Cel PM (Coronel)')], default='Sd PM', max_length=15, verbose_name='Posto/Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('num_matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula/RE')),
                ('status', models.CharField(choices=[('SERVICO', 'De Serviço (Pronto)'), ('EXPEDIENTE', 'Expediente Comum'), ('FERIAS', 'Férias'), ('LICENCA', 'Licença Médica/Tratamento'), ('DISPENSA', 'Dispensa como Recompensa/Nupcial'), ('AFASTADO', 'Outros Afastamentos')], default='EXPEDIENTE', max_length=15, verbose_name='Situação Atual')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policiais', to='vtr.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Efetivo Nominal',
                'ordering': ['unidade', 'nome_guerra'],
            },
        ),
    ]
