# Generated by Django 5.0.7 on 2024-08-12 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nome_destinatario', models.CharField(max_length=100)),
                ('cargofuncao', models.CharField(max_length=100)),
                ('posto', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('motivo', models.CharField(default=0, max_length=100)),
                ('endereco', models.CharField(default=0, max_length=100)),
                ('telefone', models.CharField(default=0, max_length=100)),
                ('texto', models.CharField(default=0, max_length=1000)),
                ('tratamento', models.CharField(default=0, max_length=100)),
                ('id_portaria', models.CharField(default=0, max_length=100)),
                ('fls', models.CharField(default=0, max_length=100)),
                ('data', models.DateField(default=datetime.date(2024, 7, 3))),
                ('hora', models.CharField(default=0, max_length=20)),
                ('data_portaria', models.DateField(default=datetime.date(2024, 7, 3))),
                ('data_inicio', models.DateField(default=datetime.date(2024, 7, 3))),
                ('dia_recebido', models.DateField(default=datetime.date(2024, 7, 3))),
                ('historico', models.TextField(max_length=2000)),
                ('usuario', models.CharField(default=0, max_length=100)),
                ('funcao_delegante', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
