# Generated by Django 5.0.7 on 2024-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_oficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='data_portaria',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='dia_recebido',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='funcao_delegante',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='historico',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='usuario',
        ),
    ]
