# Generated by Django 5.0.7 on 2024-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_oficio_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
