# Generated by Django 5.0.7 on 2024-08-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_oficio_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='numero',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
