# Generated by Django 5.0.7 on 2024-08-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_oficio_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['numero']},
        ),
    ]
