# Generated by Django 5.0.7 on 2024-08-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_oficio_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sindicancia',
            name='padrao_oficio',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
