# Generated by Django 5.0.7 on 2024-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_sindicancia_padrao_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindicancia',
            name='padrao_oficio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
