# Generated by Django 5.0.7 on 2024-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_sindicancia_padrao_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='motivo',
            field=models.CharField(max_length=10000),
        ),
    ]
