# Generated by Django 5.0.7 on 2024-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_oficio_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofendido',
            name='declaracao',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='sindicado',
            name='declaracao',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='testemunha',
            name='declaracao',
            field=models.TextField(max_length=20000),
        ),
    ]
