# Generated by Django 5.0 on 2026-04-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_alter_ofendido_declaracao_alter_sindicado_declaracao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conselho',
        ),
        migrations.DeleteModel(
            name='Ipm',
        ),
        migrations.DeleteModel(
            name='Riog',
        ),
    ]
