# Generated by Django 5.0 on 2026-08-17 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Policiamento')),
            ],
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_guerra', models.CharField(max_length=100, verbose_name='Nome de Guerra (Ex: Cb José)')),
                ('categoria', models.CharField(choices=[('SD_CB', 'Soldado / Cabo'), ('SGT_SUB', 'Sargento / Subtenente'), ('OFI', 'Oficiais')], max_length=10, verbose_name='Categoria para Pagamento')),
                ('rgpm', models.CharField(max_length=20, unique=True, verbose_name='RGPM')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('posto_graduacao', models.CharField(choices=[('SD PM', 'Sd PM'), ('CB PM', 'Cb PM'), ('3SGT PM', '3º Sgt PM'), ('2SGT PM', '2º Sgt PM'), ('1SGT PM', '1º Sgt PM'), ('SUB TEN PM', 'Sub Ten PM'), ('ASP OF PM', 'Asp Of PM'), ('2TEN PM', '2º Ten PM'), ('1TEN PM', '1º Ten PM'), ('CAP PM', 'Cap PM'), ('MAJ PM', 'Maj PM'), ('TEN CEL PM', 'Ten Cel PM'), ('CEL PM', 'Cel PM')], max_length=20, verbose_name='Posto / Graduação')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('filiacao', models.CharField(max_length=255, verbose_name='Filiação (Mãe/Pai)')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência Bancária')),
                ('conta_corrente', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta Corrente')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['nome_guerra'],
            },
        ),
        migrations.CreateModel(
            name='PontoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ponto Fixo')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Endereço/Localização')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Orientação para a Guarnição')),
            ],
        ),
        migrations.CreateModel(
            name='ValorHoraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('SD_CB', 'Soldado / Cabo'), ('SGT_SUB', 'Sargento / Subtenente'), ('OFI', 'Oficiais')], max_length=10, unique=True, verbose_name='Categoria')),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por Hora (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='CartaoPoliciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(default='19:00', verbose_name='Hora Início')),
                ('horario_fim', models.TimeField(default='01:00', verbose_name='Hora Fim')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='efetivo.escaladiaria')),
                ('comandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_comandante', to='efetivo.policial')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_motorista', to='efetivo.policial')),
                ('patrulheiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_patrulheiro', to='efetivo.policial')),
                ('ponto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.pontofixo', verbose_name='Ponto Fixo')),
            ],
        ),
    ]
