# Generated by Django 5.0 on 2026-08-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Unidade')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEscalaNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função/Posto de Serviço (Ex: Guarda da Guarda, Rádio Patrulha)')),
                ('horario_inicio', models.TimeField(default='07:00', verbose_name='Hora Início')),
                ('horario_fim', models.TimeField(default='19:00', verbose_name='Hora Fim')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='efetivo.escalanormal')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_normais', to='efetivo.policial')),
            ],
        ),
        migrations.AddField(
            model_name='escalanormal',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_normais', to='efetivo.unidade'),
        ),
        migrations.AddField(
            model_name='policial',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policiais', to='efetivo.unidade', verbose_name='Unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='escalanormal',
            unique_together={('unidade', 'data')},
        ),
    ]
