# Generated by Django 5.0 on 2026-08-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0002_escalanormal_unidade_itemescalanormal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemescalanormal',
            name='policial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_escalas_normais', to='efetivo.policial'),
        ),
    ]
