# Generated by Django 5.0 on 2026-09-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0003_alter_itemescalanormal_policial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.escaladiaria')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoHorarioCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='efetivo.cartaoprograma')),
            ],
        ),
        migrations.CreateModel(
            name='ChecagemLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_comprovacao', models.ImageField(blank=True, null=True, upload_to='cartao_programa/')),
                ('horario_registro', models.DateTimeField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='efetivo.blocohorariocartao')),
                ('ponto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.pontofixo')),
            ],
        ),
    ]
