# Generated by Django 5.0 on 2026-06-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('comandante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comandante da GUPM')),
                ('componente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Componente da GUPM')),
                ('natureza_ocorrencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Natureza da Ocorrência')),
                ('detalhes_ocorrencia', models.TextField(blank=True, null=True, verbose_name='Detalhes da Ocorrência')),
                ('pessoas_abordadas', models.IntegerField(default=0, verbose_name='Pessoas Abordadas')),
                ('veiculos_abordados', models.IntegerField(default=0, verbose_name='Veículos Abordados')),
                ('notificacoes', models.IntegerField(default=0, verbose_name='Notificações Aplicadas')),
                ('veiculos_apreendidos', models.IntegerField(default=0, verbose_name='Veículos Apreendidos')),
                ('tco', models.IntegerField(default=0, verbose_name='TCO Confeccionados')),
                ('pessoas_conduzidas', models.IntegerField(default=0, verbose_name='Pessoas Conduzidas')),
                ('starts', models.IntegerField(default=0, verbose_name='Starts Realizados')),
                ('barreiras', models.IntegerField(default=0, verbose_name='Barreiras Realizadas')),
            ],
            options={
                'verbose_name': 'Registro Diário',
                'verbose_name_plural': 'Registros Diários',
            },
        ),
        migrations.CreateModel(
            name='MaterialApreendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=100, verbose_name='Tipo (ex: Droga, Arma)')),
                ('natureza_especifica', models.CharField(max_length=100, verbose_name='Natureza (ex: Cocaína)')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade (ex: petecas, gramas, un)')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='produtividade.registrodiario')),
            ],
            options={
                'verbose_name': 'Material Apreendido',
                'verbose_name_plural': 'Materiais Apreendidos',
            },
        ),
    ]
