# Generated by Django 5.0 on 2026-06-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Natureza da Ocorrência')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo (ex: Droga, Arma)')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Unidade (ex: petecas, gramas)')),
            ],
        ),
        migrations.AlterField(
            model_name='materialapreendido',
            name='natureza_especifica',
            field=models.CharField(max_length=100, verbose_name='Ex: Cocaína, Maconha'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='natureza_ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtividade.naturezaocorrencia', verbose_name='Natureza da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='materialapreendido',
            name='tipo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtividade.tipomaterial', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materialapreendido',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtividade.unidademedida', verbose_name='Unidade'),
        ),
    ]
