# Generated by Django 5.0 on 2026-06-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0002_naturezaocorrencia_tipomaterial_unidademedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapreendido',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='produtividade.registrodiario', verbose_name='Registro de Origem'),
        ),
    ]
