# Generated by Django 5.0 on 2026-06-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0003_alter_materialapreendido_ocorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialapreendido',
            name='natureza_especifica',
        ),
    ]
