# Generated by Django 5.0 on 2026-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0004_remove_materialapreendido_natureza_especifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterial',
            name='cor',
            field=models.CharField(default='#36a2eb', max_length=7, verbose_name='Cor (Hexadecimal)'),
        ),
    ]
