# Generated by Django 5.0 on 2026-06-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0005_tipomaterial_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProdutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria (ex: Escolas Visitadas)')),
                ('cor', models.CharField(default='#36a2eb', max_length=7, verbose_name='Cor (Hex)')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='barreiras',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='notificacoes',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='pessoas_abordadas',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='pessoas_conduzidas',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='tco',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='veiculos_abordados',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='veiculos_apreendidos',
        ),
        migrations.AlterField(
            model_name='materialapreendido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='cor',
            field=models.CharField(default='#36a2eb', max_length=7, verbose_name='Cor (Hex)'),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='ValorProdutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtividade.categoriaprodutividade')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='produtividade.registrodiario')),
            ],
        ),
    ]
