# Generated by Django 5.0 on 2026-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0006_categoriaprodutividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturezaocorrencia',
            name='cor',
            field=models.CharField(default='#36a2eb', max_length=7, verbose_name='Cor (Hex)'),
        ),
    ]
